name: Stage
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop", "staging" ]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/project

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build

      - name: Store binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ${{github.workspace}}/project

  unit-tests:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
      - name: Unit Tests
        working-directory: bin
        run: |
          chmod 755 ./technion-234124_tests_exc
          ./technion-234124_tests_exc
  case-tests:
    name: Case tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Pull tests
        run: |
          git clone --branch tests https://gitlab.com/jamalabo1/technion-utils bin/hw1

      - name: Install depends
        run: pip install -U pytest

      - name: Case tests
        working-directory: bin
        run: |
          pytest engine/runner2.py --capture=no

      - name: Archive Results
        uses: actions/upload-artifact@v4
        with:
          name: tests
          path: ./bin/**/*.out

  valgrind-tests:
    name: Valgrind tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Setup valgrind
        run: |
              sudo apt-get update
              sudo apt-get install -y valgrind

      - name: Pull tests
        run: |
          git clone --branch tests https://gitlab.com/jamalabo1/technion-utils bin/hw1


      - name: Install depends
        run: pip install -U pytest

      - name: Valgrind Test
        working-directory: bin
        run: |
          ls
          pytest --valgrind engine/runner2.py --verbose --capture=tee-sys
