name: Stage
on:
  workflow_call:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
jobs:
  build:
    container:
      image: danger89/cmake:latest
    runs-on: docker
    steps:
      - name: Build
        run:  mkdir /home/project && cmake -G Ninja -B /home/project/build
      - name: Store binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: /home/project/build
  valgrind:
    timeout-minutes: 45
    name: Valgrind 3.19.0
    needs: build
    runs-on: docker
    container:
      image: jamalabo1/valgrind:latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
      - name: Valgrind Test
        env:
          TEST_COMMAND: ${{ inputs.test_command }}
        run: valgrind --leak-check=full /home/project/build/